import type { MarketEntryAnalysis } from "./marketEntry"

export function getMockMarketEntryAnalysis(): MarketEntryAnalysis {
  return {
    generatedAt: new Date().toISOString(),
    readinessScore: 42,
    pillars: [
      {
        id: "compliance_tax",
        label: "Compliance & Tax",
        score: 30,
        insight: "High risk: SFA import permit requires a local entity or IOR; label compliance (English, allergens, batch number) and preservative limits not yet confirmed.",
      },
      {
        id: "finance_ops",
        label: "Finance & Operations",
        score: 45,
        insight: "GST and customs duty treatment unclear; import model (Incoterms, duty valuation) needs accountant review; cash flow must account for upfront compliance costs.",
      },
      {
        id: "localization",
        label: "Localization",
        score: 38,
        insight: "Labels need a full overhaul (English, allergens, 2026 batch number requirement); Halal strategy undecided; content compliance playbook not yet established.",
      },
      {
        id: "tiktok_social_commerce",
        label: "TikTok / Social Commerce",
        score: 55,
        insight: "Chili sauce suits short-form video, but TikTok Shop listings must comply with HPB/IMDA health claim rules — no exaggerated efficacy claims.",
      },
      {
        id: "execution",
        label: "Execution Readiness",
        score: 42,
        insight: "6 high-risk items to resolve. Prioritize: local entity/IOR, label compliance, and preservative testing — without these, import cannot begin.",
      },
    ],
    checklist: [
      {
        id: "c1",
        category: "Compliance",
        title: "Confirm SFA food import permit pathway and required documentation",
        ownerRole: "founder",
        priority: "P0",
        evidence: "SFA importer registration form, company incorporation documents",
        dueSuggestion: "Week 0-2",
        status: "todo",
        linkedRiskIds: ["r1"],
      },
      {
        id: "c2",
        category: "Compliance",
        title: "Label compliance audit: English ingredients list, nutrition info, allergen declarations",
        ownerRole: "growth",
        priority: "P0",
        evidence: "Product ingredient spec, nutrition lab report, label artwork draft",
        dueSuggestion: "Week 1-3",
        status: "todo",
        linkedRiskIds: ["r3"],
      },
      {
        id: "c3",
        category: "Tax",
        title: "GST registration assessment: projected 12-month revenue vs SGD 1M threshold",
        ownerRole: "accountant",
        priority: "P0",
        evidence: "12-month revenue forecast with channel breakdown",
        dueSuggestion: "Week 1-3",
        status: "todo",
        linkedRiskIds: ["r2"],
      },
      {
        id: "c4",
        category: "Finance",
        title: "First shipment cost model: production, freight, customs duty, warehousing",
        ownerRole: "accountant",
        priority: "P0",
        evidence: "Supplier quotes, freight comparison, customs duty rate sheet",
        dueSuggestion: "Week 2-4",
        status: "todo",
      },
      {
        id: "c5",
        category: "Operations",
        title: "Confirm logistics setup: sea vs air freight, ambient vs cold chain, customs broker",
        ownerRole: "founder",
        priority: "P0",
        evidence: "Quotes from at least 2 freight forwarders with lead time comparison",
        dueSuggestion: "Week 2-4",
        status: "todo",
        linkedRiskIds: ["r4"],
      },
      {
        id: "c6",
        category: "Operations",
        title: "Shortlist and sign Singapore local warehouse / distribution partner",
        ownerRole: "founder",
        priority: "P1",
        evidence: "Distributor shortlist with term sheet comparison",
        dueSuggestion: "Week 3-5",
        status: "todo",
      },
      {
        id: "c7",
        category: "Localization",
        title: "Product localization: English name, heat level system (Mild / Medium / Hot), usage descriptions",
        ownerRole: "growth",
        priority: "P0",
        evidence: "Final English label artwork, heat level standard document",
        dueSuggestion: "Week 3-5",
        status: "todo",
        linkedRiskIds: ["r5"],
      },
      {
        id: "c8",
        category: "TikTok",
        title: "Define 3 content pillars + 14-day content calendar (taste test / recipe pairings / behind-the-scenes)",
        ownerRole: "growth",
        priority: "P0",
        evidence: "Content calendar + 10 script templates",
        dueSuggestion: "Week 4-6",
        status: "todo",
      },
      {
        id: "c9",
        category: "TikTok",
        title: "Set up TikTok Shop and Shopee storefronts with optimized product listings",
        ownerRole: "growth",
        priority: "P0",
        evidence: "Store registration docs, product detail page copy",
        dueSuggestion: "Week 4-6",
        status: "todo",
      },
      {
        id: "c10",
        category: "TikTok",
        title: "Creator collaboration brief: product USPs, shooting guidelines, commission model",
        ownerRole: "growth",
        priority: "P1",
        evidence: "Creator shortlist + partnership term template",
        dueSuggestion: "Week 5-7",
        status: "todo",
      },
      {
        id: "c11",
        category: "Tax",
        title: "Confirm import duty rates and certificate of origin requirements",
        ownerRole: "accountant",
        priority: "P1",
        evidence: "HS code confirmation, certificate of origin",
        dueSuggestion: "Week 2-4",
        status: "todo",
      },
    ],
    risks: [
      {
        id: "r1",
        area: "Regulatory",
        risk: "Overseas brands cannot apply directly for an SFA import permit — a Singapore-registered entity and a local Importer of Record (IOR) are required. Without this, import permits cannot be obtained and shipments may be delayed or refused.",
        impact: "high",
        likelihood: "high",
        mitigation: "Determine market entry structure (local entity vs distributor/IOR). Appoint a Singapore-registered IOR. Complete import permit application, product documentation, and role assignments before first shipment.",
        regulatorySource: "Singapore Food Agency (SFA) — processed food import requirements; Singapore Customs import procedures",
        ownerRole: "founder",
        status: "open",
      },
      {
        id: "r2",
        area: "Labelling",
        risk: "Packaging labels missing mandatory information or in Chinese only — retail partners will refuse to list, or costly re-labeling will be required.",
        impact: "high",
        likelihood: "high",
        mitigation: "Conduct a label gap assessment against Singapore requirements (English label, ingredients list, net weight, country of origin, local importer/distributor name and address, expiry date). Complete compliant re-label or packaging revision before retail listing.",
        regulatorySource: "Singapore Food Regulations — labeling requirements (SFA regulated)",
        ownerRole: "growth",
        status: "open",
      },
      {
        id: "r2b",
        area: "Labelling",
        risk: "From 30 Jan 2026, pre-packaged food labels that do not include a batch/lot identifier and country-of-origin declaration will be non-compliant and face delisting and enforcement risk.",
        impact: "high",
        likelihood: "high",
        mitigation: "Update packaging design and/or relabeling SOP to add batch identifier and country of origin on every SKU. Establish batch coding and traceability controls with manufacturer and Singapore IOR/distributor.",
        regulatorySource: "SFA Food (Amendment) Regulations 2025 — effective 30 Jan 2026, Regulation 5",
        ownerRole: "growth",
        status: "open",
      },
      {
        id: "r3",
        area: "Labelling",
        risk: "Allergen declarations and ingredient naming may be incorrect or incomplete (e.g. soy, sesame, peanuts, gluten), creating consumer safety risk and regulatory exposure.",
        impact: "high",
        likelihood: "medium",
        mitigation: "Obtain verified allergen declarations from the manufacturer. Map ingredients to Singapore's allergen declaration system. Standardize English ingredient names. Establish a supplier change control process to keep labels in sync.",
        regulatorySource: "SFA food allergen labeling guidelines; Singapore Food Regulations — ingredients list requirements",
        ownerRole: "growth",
        status: "open",
      },
      {
        id: "r4",
        area: "Halal",
        risk: "Halal-sensitive ingredients or production cross-contamination risk may limit distribution to Muslim consumers (~15% of Singapore population). Implied Halal claims without certification could trigger complaints.",
        impact: "medium",
        likelihood: "medium",
        mitigation: "Decide whether to pursue Halal certification. If yes, verify whether the Chinese certifier is on MUIS's list of 101 recognized overseas Halal bodies (fhcb.muis.gov.sg). If no, avoid any Halal-implied wording or visuals on packaging and TikTok Shop.",
        regulatorySource: "MUIS Halal Certification Scheme; MUIS overseas Halal certifier recognition program",
        ownerRole: "founder",
        status: "watch",
      },
      {
        id: "r5",
        area: "Tax",
        risk: "GST and customs duty valuation on imports and local sales may be handled incorrectly, leading to underpayment, penalties, or cash flow surprises.",
        impact: "medium",
        likelihood: "medium",
        mitigation: "Have an accountant review the import model (IOR, Incoterms, customs valuation). Confirm whether GST registration is required based on projected taxable turnover. Set up bookkeeping to separate import GST, input tax credits, and TikTok Shop platform fees.",
        regulatorySource: "IRAS GST rules; Singapore Customs import duty / GST guidelines",
        ownerRole: "accountant",
        status: "open",
      },
      {
        id: "r6",
        area: "Entity",
        risk: "Without an appropriate local entity or contract structure, supermarket onboarding may be blocked, liability allocation becomes complex, and disputes over recalls, returns, and indemnification may arise.",
        impact: "medium",
        likelihood: "medium",
        mitigation: "Choose market entry structure (local subsidiary vs distributor/IOR). Ensure contracts clearly allocate responsibilities (product liability, recalls, labeling, returns). Prepare standard vendor onboarding documents (UEN, bank account, insurance where required).",
        regulatorySource: "ACRA company registration requirements; Singapore retailer vendor onboarding standards",
        ownerRole: "founder",
        status: "watch",
      },
      {
        id: "r7",
        area: "Content",
        risk: "TikTok Shop content or product listings may contain prohibited or high-risk claims (e.g. 'cures', 'health benefits', 'best for weight loss'), triggering takedowns, complaints, or regulatory review.",
        impact: "high",
        likelihood: "medium",
        mitigation: "Build a content claims safe-list and red-flag list. All health-related language must go through a pre-publish review. Reframe copy around flavor, usage occasions, and ingredients — avoid any medical or efficacy claims.",
        regulatorySource: "HPB food advertising guidelines; IMDA content standards; TikTok Shop Singapore listing and advertising policies",
        ownerRole: "growth",
        status: "open",
      },
      {
        id: "r8",
        area: "Regulatory",
        risk: "Food safety test documentation (e.g. microbial or contaminant COAs) may be requested by retail partners or authorities — inability to provide will delay listing or shipment.",
        impact: "low",
        likelihood: "low",
        mitigation: "Collect recent third-party lab test reports / COAs and maintain a documentation pack (batch traceability, shelf-life rationale, storage conditions) ready for supermarket and SFA inquiries.",
        regulatorySource: "SFA risk-based food safety requirements and inspection / enforcement practices",
        ownerRole: "founder",
        status: "watch",
      },
      {
        id: "r9",
        area: "Regulatory",
        risk: "If sodium benzoate in the chili sauce exceeds the maximum permitted level for the relevant condiment category under the Fourth Schedule, the product is non-compliant and cannot be legally sold — reformulation required.",
        impact: "high",
        likelihood: "medium",
        mitigation: "Obtain exact preservative concentrations per serving and per kg from the manufacturer (COA / spec sheet). Map the product to the correct Singapore food category to confirm permitted limits. Adjust levels or reformulate before importing and listing on retail / TikTok Shop. Retain documentation for SFA / retailer due diligence.",
        regulatorySource: "SFA Food Regulations Regulation 19; Fourth Schedule (maximum permitted preservative levels, including sodium benzoate)",
        ownerRole: "founder",
        status: "open",
      },
    ],
    localization: [
      {
        area: "Brand",
        suggestion: "English brand positioning: 'Authentic Hunan Chili Sauce — Bold Flavor, Your Level of Heat'",
        rationale: "Highlights authentic Hunan origin and controllable heat, lowering the trial barrier for Singapore consumers unfamiliar with the brand.",
      },
      {
        area: "Menu",
        suggestion: "Product line naming: Classic Duo Jiao / Spicy Beef Sauce / Garlic Chili Crisp, with a 1–3 chili heat indicator",
        rationale: "English names with a visual heat scale reduce purchase anxiety and make comparisons easy on e-commerce listings.",
      },
      {
        area: "Copy",
        suggestion: "Use a one-line hook format for product descriptions: core USP + pairing suggestion (e.g. 'Perfect on rice, noodles, or as a dip')",
        rationale: "Short-form copy works better for e-commerce detail pages and short-video captions — keep it scannable.",
      },
      {
        area: "Pricing",
        suggestion: "Offer a trial size (50ml) + full size (280ml) + gift set (3-pack) to cover first-trial and repeat purchase scenarios",
        rationale: "Trial size lowers first-purchase risk; gift set suits social commerce promotions and seasonal gifting.",
      },
      {
        area: "Operational",
        suggestion: "Add a 'Pairing Ideas' section to e-commerce pages covering four key occasions: with rice / noodles / as a dip / stir-fry",
        rationale: "Helps consumers unfamiliar with Chinese chili sauce quickly understand use cases, improving conversion.",
      },
    ],
    tiktokActions: [
      {
        phase: "Week0",
        title: "Define account positioning and 3 content pillars: heat challenge / recipe pairing / factory behind-the-scenes",
        why: "Let the algorithm recognize your content category early; serializable formats improve content reuse and consistency.",
        ownerRole: "growth",
        artifacts: ["Content pillar brief", "Shoot location checklist"],
      },
      {
        phase: "Week0",
        title: "Set up TikTok Shop and Shopee storefronts with optimized listings and product detail pages",
        why: "Ensure content seeding has a direct conversion path before launch.",
        ownerRole: "growth",
        artifacts: ["Storefront setup template", "Product detail page copy"],
      },
      {
        phase: "Week1",
        title: "First 7 days: 1 product USP video + 1 recipe tutorial per day (alternating)",
        why: "Product content drives conversion; tutorials build utility and differentiation.",
        ownerRole: "growth",
        artifacts: ["7-day content calendar"],
      },
      {
        phase: "Week1",
        title: "3–5 local food creator partnerships: send samples + creator brief",
        why: "Third-party endorsement lowers first-purchase hesitation.",
        ownerRole: "growth",
        artifacts: ["Creator brief", "Commission and terms template"],
      },
      {
        phase: "Week2",
        title: "First livestream: 'Blind heat test challenge' + limited-time bundle offer",
        why: "Livestream engagement builds loyalty; limited offers accelerate first orders.",
        ownerRole: "founder",
        artifacts: ["Livestream runsheet", "FAQ list"],
      },
      {
        phase: "Week2",
        title: "Paid test: 2 video creatives x 2 audiences x conversion objective (low budget)",
        why: "Validate creative direction at minimum cost before scaling spend.",
        ownerRole: "accountant",
        artifacts: ["Ad hypothesis sheet", "Budget cap rules"],
      },
      {
        phase: "AlwaysOn",
        title: "Weekly review: content metrics, store conversion, negative review themes, product iteration direction",
        why: "Turn growth into an operational rhythm, not a one-off campaign.",
        ownerRole: "founder",
        artifacts: ["Weekly review template"],
      },
    ],
    advisorExport: {
      executiveSummary:
        "This chili sauce brand scores 42 readiness — 6 high-risk items need resolving before launch. Key blockers: SFA import permit requires a local entity or IOR; labels need a full overhaul (English, allergens, 2026 batch number rule, preservative compliance); TikTok content needs a compliance playbook. Recommended path: spend 4 weeks locking in compliance (entity/IOR + label revision + preservative testing), then launch TikTok + Shopee dual-channel content plan.",
      keyDecisions: [
        "Import pathway: apply for SFA permit directly vs use a local distributor / IOR",
        "GST: conservative 12-month revenue projection and registration strategy",
        "Product localization: English naming + heat level system + label compliance",
        "Channel strategy: TikTok Shop + Shopee first, then expand to premium supermarkets",
        "Growth approach: validate content direction via UGC / creator partnerships before paid spend",
      ],
      appendixNotes: [
        "Demo data is AI-generated and illustrates cross-role collaboration and deliverable structure",
        "Once backend is connected, real-time regulatory and market data will replace these recommendations",
      ],
    },
  }
}
